### ISSUE TITLE
Being detected

### ISSUE THREAD

**Issue by Whi7eSun** [Taiga74164/SLA-Cheeto#123]
Hey Taiga,
Sorry to bother, but it seems that the SLA Cheeto is being detected and people are being banned, even thought they're using it story mode.
Do you happen to know anything about it? Have you sorted it out?
Thanks in advance! You're the best!

**Comment by Taiga74164** [comment]
This repo is fully updated to the latest version. However, it does not provide any detection bypass. Im not responsible for any bans and I'm strongly against publishing a bypass on a public repo to prevent devs from patching it. Either you figure it out yourself or use forks of this project. A lot of them are actually posted in Unknowncheats or Discord servers.

At its current state, this repo is for dev purposes ONLY. This project serves as a starting point for people getting into game hacking. Only offsets will be updated since I can do it automatically using my tool every patch.
